name: Build an test app

on:
  push:
      branches:
      - CITravisDownFix

jobs:
  build-and-deploy:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Java version
      uses: actions/setup-java@v1
      with:
        java-version: '11'

    - name: Build and inspect
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      run: |
        cd uwind
        chmod +x mvnw
        mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent initialize sonar:sonar verify sonar:sonar -Pcoverage -Dsonar.projectKey=2020-2021-ECOM-INFO5-G04_App -Dsonar.login=${{ secrets.SONAR_TOKEN }}